# config.make generated by configure script
POCO_CONFIG = Linux
POCO_BASE = /home/anton/Programs/PocoTestProject/poco-1.7.5
POCO_BUILD = /home/anton/Programs/PocoTestProject/poco-1.7.5
POCO_FLAGS = 
POCO_PREFIX = /usr/local
OMIT = Data/ODBC Data/MySQL MongoDB PDF CppParser
LINKMODE = STATIC
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_FLAGS
export POCO_PREFIX
export LINKMODE
