//
// Created by anton on 19.04.19.
//

#ifndef COOLSTEALNIGHT_TOKENTYPE_H
#define COOLSTEALNIGHT_TOKENTYPE_H
enum TokenType {
  KEYWORD,
  VARIABLE_TYPE,
  VALUE_TYPE,
  IDENTIFICATOR,
  OPERATOR,
  CYCLE,
  CONDITION
};
#endif //COOLSTEALNIGHT_TOKENTYPE_H
