//
// Created by anton on 19.04.19.
//

#ifndef COOLSTEALNIGHT_TOKENTYPE_H
#define COOLSTEALNIGHT_TOKENTYPE_H
enum TokenType{
    KEYWORD,
    VARIABLE_TYPE,
    NUMBER,
    IDENTIFICATOR,
    OPERATOR,
    CYCLE
};
#endif //COOLSTEALNIGHT_TOKENTYPE_H
